#!/usr/bin/env python3
import os, hashlib, sys, uuid
passw = uuid.uuid4().hex
with open(os.path.join(os.environ["CHATTER_USERS_DIR"], sys.argv[1]), "w") as passwf: passwf.write(hashlib.sha256(passw.encode("ascii")).hexdigest())
print(passw)
