#!/usr/bin/env python3
import wsgiref.simple_server, os, hashlib, shutil, traceback, datetime
def app(env, begin):
    try:
        rbias_bytes, uname, passw, rname, msg = [env["wsgi.input"].readline()[:-1] for _ in range(5)]
        assert os.path.basename(uname) == uname and os.path.basename(rname) == rname
        with open(os.path.join(os.fsencode(os.environ["CHATTER_USERS_DIR"]), uname), "rb") as passwf: assert passwf.read().strip() == hashlib.sha256(passw).hexdigest().encode("ascii")
        rbias = int(rbias_bytes.decode("ascii"))
        roomf = open(rname, "a+b" if msg else "rb")
        begin("200 OK", [])
        if msg: roomf.write(datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S").encode("ascii") + b" " + uname + b": " + msg + b"\n")
        roomf.seek(rbias)
        return roomf
    except Exception:
        begin("400 Bad Request", [])
        raise
wsgiref.simple_server.make_server(os.environ["CHATTER_HOST"], int(os.environ["CHATTER_PORT"]), app).serve_forever()
